export const TABLE_TYPES = [
  'SQUARE_TABLES',
  'RECTANGLE_TABLES',
  'CIRCLE_TABLES'
];

export const SQUARE_TABLES = 'SQUARE_TABLES';
export const RECTANGLE_TABLES = 'RECTANGLE_TABLES';
export const CIRCLE_TABLES = 'CIRCLE_TABLES';
