// General
export const FETCH_INITIAL_DATA = 'FETCH_INITIAL_DATA';
export const SAVE_DATA = 'SAVE_DATA';


// Canvas
export const CANVAS_ITEM_UPDATE = 'CANVAS_ITEM_UPDATE';
export const CANVAS_ITEM_SELECTED = 'CANVAS_ITEM_SELECTED';
export const CANVAS_ITEM_DESELECTED = 'CANVAS_ITEM_DESELECTED';
export const CANVAS_ITEM_ADD = 'CANVAS_ITEM_ADD';
export const CANVAS_ITEM_REMOVE = 'CANVAS_ITEM_REMOVE';
export const CANVAS_ITEM_SET_WIDTH = 'CANVAS_ITEM_SET_WIDTH';
export const CANVAS_ITEM_SET_HEIGHT = 'CANVAS_ITEM_SET_HEIGHT';
export const CANVAS_ITEM_SET_SIZE = 'CANVAS_ITEM_SET_SIZE';
export const CANVAS_ITEM_SET_ROTATION = 'CANVS_ITEM_SET_ROTATION';
export const CANVAS_ITEM_DUPLICATE = 'CANVAS_ITEM_DUPLICATE';
export const CANVAS_ITEM_SET_COLOR = 'CANVAS_ITEM_SET_COLOR';
export const CANVAS_ITEM_SET_POSITION = 'CANVAS_ITEM_SET_POSITION';
export const CANVAS_ITEM_SET_DISPLAY_NAME = 'CANVAS_ITEM_SET_DISPLAY_NAME';
export const CANVAS_ITEM_SET_FONT_SIZE = 'CANVAS_ITEM_SET_FONT_SIZE';

export const CANVAS_ZOOM_IN = 'CANVAS_ZOOM_IN';
export const CANVAS_ZOOM_OUT = 'CANVAS_ZOOM_OUT';
export const CANVAS_ZOOM_RESET = 'CANVAS_ZOOM_RESET';
export const CANVAS_MOVE_RIGHT = 'CANVAS_MOVE_RIGHT';
export const CANVAS_MOVE_LEFT = 'CANVAS_MOVE_LEFT';
export const CANVAS_MOVE_UP = 'CANVAS_MOVE_UP';
export const CANVAS_MOVE_DOWN = 'CANVAS_MOVE_DOWN';

export const SEAT_SELECT = 'SEAT_SELECT';
export const SEAT_UPDATE = 'SEAT_UPDATE';


export const SEAT_RESERVE = 'SEAT_RESERVE';
export const SEAT_RESERVE_SINGLE_CHAIR = 'SEAT_RESERVE_SINGLE_CHAIR';
export const UNSEAT_RESERVE_SINGLE_CHAIR = 'UNSEAT_RESERVE_SINGLE_CHAIR';
export const UNSEAT_RESERVE = 'UNSEAT_RESERVE';
export const SEAT_BOOK = 'SEAT_BOOK';
export const SEAT_BOOK_SINGLE_CHAIR = 'SEAT_BOOK_SINGLE_CHAIR';
export const SEAT_BOOK_CANCEL = 'SEAT_BOOK_CANCEL';
export const SEAT_BOOK_CANCEL_SINGLE_CHAIR = 'SEAT_BOOK_CANCEL_SINGLE_CHAIR';

// Floors
export const FLOOR_ADD = 'FLOOR_ADD';
export const FLOOR_REMOVE = 'FLOOR_REMOVE';
export const FLOOR_CHANGE = 'FLOOR_CHANGE';

export const LOAD_GUESTS = 'LOAD_GUESTS';
